### PR TITLE
document the `excludes` option for dump

### PR DESCRIPTION
**Pull request by simbabque**
It would probably make sense to make it smart enough to ignore views automatically because those error when they are populated.

### CODE REVIEW

**Comment by ediblenergy** [comment]
merged, fixed a small typo in the pr which is displaying as a github conflict here.

**Comment by samuelkaufman** [comment]
it's live now.

**Comment by simbabque** [comment]
I am not sure how you merged it without the PR marking as merged, but it's in. Thanks! :)

**Comment by samuelkaufman** [comment]
@simbabque has to do with the modification I made to your pr I guess? https://github.com/dbsrgits/DBIx-Class-Fixtures/commit/627108dfb588d5db3f2646c170eee379c80d96d4

Not really sure either.

**Comment by simbabque** [comment]
It also says here that there are unmerged commits in my branch. How strange.

**Pull request closed without merging**
